---
output:
  html_document:
    keep_md: true
---


#### Setup

```{r message=FALSE}

library(data.table)
library(dplyr)

library(rbenchmark)
set.seed(123)

```


#### Generate data

```{r}

n <- 10e6
m <- 1e4

benchmark(
  d <- data_frame(x = sample(m, n, replace=TRUE), y = runif(n)),
  dt <- tbl_dt(d),
  dtk <- tbl_dt(d),
  setkey(dtk,x),
  dm <- data_frame(x = sample(m)),
  dtm <- tbl_dt(dm),
replications=1, columns=c("test", "elapsed"), order=NULL)

```


#### Filter

```{r}

benchmark(
  d[d$x>=10 & d$x<20,],
  d %>% filter(x>=10, x<20),
  dt %>% filter(x>=10, x<20),
  dtk %>% filter(x>=10, x<20),
  dt[x>=10 & x<20],
  dtk[x>=10 & x<20],
replications=1, columns=c("test", "elapsed", "relative"), order=NULL)

```

maybe dt has some tricks to use the "key" for ranges?


#### Sort

```{r}

benchmark(
  d[order(d$x),],
  d %>% arrange(x),
  dt %>% arrange(x),
  dtk %>% arrange(x),
  dt[order(x)],  
  dtk[order(x)],
replications=1, columns=c("test", "elapsed", "relative"), order=NULL)

```


#### New column

```{r}

benchmark(
  d$y2 <- 2*d$y,
  d %>% mutate(y2 = 2*y),
  dt %>% mutate(y2 = 2*y),
  dtk %>% mutate(y2 = 2*y),
  dt[,y2 := 2*y],
  dtk[,y2 := 2*y],
replications=1, columns=c("test", "elapsed", "relative"), order=NULL)
invisible(dt[,y2 := NULL])
invisible(dtk[,y2 := NULL])

```


#### Aggregate

```{r}

benchmark(
  tapply(d$y, d$x, mean),
  d %>% group_by(x) %>% summarize(ym = mean(y)),
  dt %>% group_by(x) %>% summarize(ym = mean(y)),
  dtk %>% group_by(x) %>% summarize(ym = mean(y)),
  dt[, mean(y), by=x],
  dtk[, mean(y), by=x],
replications=1, columns=c("test", "elapsed", "relative"), order=NULL)

```


#### Joins

```{r}

benchmark(
  # merge(d,dm, by="x"),
  d %>% inner_join(dm, by="x"),
  dt %>% inner_join(dtm, by="x"),
  dtk %>% inner_join(dtm, by="x"),
  dtk[dtm, nomatch=0],
replications=1, columns=c("test", "elapsed", "relative"), order=NULL)

```

base is too slow (>100x)




